### ISSUE TITLE
Single Operation

### ISSUE THREAD

**Issue by prasannavl** [reactiveui/punchclock#10]
First off, Simple, yet very elegant library! 

The string keys preventing concurrent operations of the same key, is a very nice feature. I'd very much like to see a feature where there can be a restriction to also ignore operations with the same key if one already exists in the queue, equal to, or higher than the given priority.

This could be immensely useful in repeated operations, where you don't keep adding similar ops to the queue if one already exists. 

Thoughts?

**Comment by megakid** [comment]
@paulcbetts I am also very interested in this feature.  Does anyone here have an implementation for this?

**Comment by ghuntley** [comment]
@prasannavl @rintje @megakid we are preparing for a new release of punchclock (upgrade to netstandard v1.0 and implement CI) - if you're interested in taking lead position (with oversight/mentorship from Paul) in implementing this please let us know.

**Comment by giusepe** [comment]
I close this issue cause it seems a bit out the scope to me and since no one mentioned about it in the last 2 (3?) years, there's no reason to keep it open.
If anyone is willing to take this further and try to implement it in a way that won't break what we currently have , I'm more than glad to look into it.
